import CategoriesList from "@/components/list/CategoriesList";
import LatestProductsList from "@/components/list/LatestProductsList";
import { Metadata } from "next";

import "./style.scss";

export const metadata: Metadata = {
  title: "Elegant parfume | Home",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <main>
      <div className="container">
        <div>
          <LatestProductsList />
        </div>
        <div>
          <CategoriesList />
        </div>
      </div>
    </main>
  );
};

export default HomePage;
