import { Metadata } from "next";
import ProductsList from "@/components/list/ProductsList";

export const metadata: Metadata = {
  title: "Elegant parfume | Products",
  description: "Generated by create next app",
};

const AllProductsPage = () => {
  return (
    <main className="publicMain">
      <div className="container">
        <ProductsList />
      </div>
    </main>
  );
};

export default AllProductsPage;
