import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Elegant parfume | Products",
  description: "Generated by create next app",
};

const AllProductsPage = () => {
  return <div>AllProductsPage</div>;
};

export default AllProductsPage;
